name: GitHub Actions Ex2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: wlroh/file-generator

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Move jar file
        run: |
          cp ${{ github.workspace }}/build/libs/file-generator-1.0.jar ${{ github.workspace }}

      - name: Generate File
        run: |
          java -jar ${{ github.workspace }}/file-generator-1.0.jar

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: List files in the output
        run: |
          ls ${{ github.workspace }}/output
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
